[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  links2004/WebSockets@^2.6.1
  adafruit/Adafruit NeoPixel@^1.12.3
